name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend
        run: |
          docker build -t mikolo01/portfolio-backend ./backend
          docker push mikolo01/portfolio-backend

      - name: Build & Push Frontend
        run: |
          docker build -t mikolo01/portfolio-frontend ./frontend
          docker push mikolo01/portfolio-frontend

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Minikube
        run: |
          kubectl apply -f ./k8s
